{
  "hash": "673077bb1d5e27ab19741e7cdecb58f9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Day 3\"\ntitle-slide-attributes:\n  data-background-image: images/lake.jpg\n  data-background-size: contain\n  data-background-opacity: \"0.5\"\nsubtitle: \"Math 216: Statistical Thinking\"\nauthor: \"Bastola\"\nformat:\n  revealjs: \n    theme: [default, scss/main.scss]\n    slide-number: true\n    preview-links: auto\n    history: true\n    chalkboard: \n      src: drawings.json\n    transition: slide\n    background-transition: fade    \n    touch: false\n    controls: true\n---\n\n\n\n\n\n\n\n# Descriptive Statistics\n\n::: bqt\n- In order to make sense of data, we need ways to **summarize and visualize** it\n- Summarizing and visualizing variables and relationships between two variables is often known as **descriptive statistics**, also known as **exploratory data analysis (EDA)**\n- The type of summary statistics and visualization methods depend on the type of variable(s) being analyzed (qualitative or quantitative)\n:::\n\n\n## One qualitative Variable\n\n::: green-h\nA random sample of US adults in 2012 were surveyed regarding the type of cell phone owned\n:::\n\n<center>\n<img src=\"images/cellphone.png\" width=\"70%\" height=\"70%\"> <br>\n<a>Android?  iPhone?  Blackberry? Non-smartphone?  No cell phone?\n</a>\n</center>\n\n\n\n\n\n## Frequency Table\n\n::: font70\n\nA frequency table shows the number of cases or counts that fall\nin each category:\n\n::: row\n::: left\n\n::: table-colored\n\n| Subset of Raw Data | Device Type             |\n|--------------------|-------------------------|\n| Case 1             | Android                 |\n| Case 2             | none                    |\n| Case 3             | none                    |\n| Case 4             | iPhone                  |\n| Case 5             | Non Smartphone          |\n| Case 6             | iPhone                  |\n| Case 7             | Blackberry              |\n| Case 8             | Non Smartphone          |\n| Case 9             | Android                 |\n| Case 10            | Android                 |\n| ...                | (for 2253 cases ...)    |\n:::\n:::\n\n\n::: right\n::: table-colored\n Cell Phone Type  | Frequency \n------------- | -------------\nAndroid  | 458\niPhone  | 437\nBlackberry | 141\nNon Smartphone | 924\nNo Cell Phone | 293\nTotal | 2253\n:::\n:::\n:::\n\n\n:::\n\n\n\n## Proportion\n\nThe proportion in a category is found by $$\\text{proportion} = \\frac{\\text{number in category}}{\\text{total sample size}}$$\n\n\n\n\n::: lqt\nPercentages/proportions  (relative frequencies)\n\n- $p$ = proportion for a [population (parameter)]{.bold-red}\n- $\\hat{p}$ = proportion for a [sample (statistic) (\"p-hat\")]{.bold-red}\n:::\n\n\n## What proportion of adults sampled do not own a cell phone?\n\n::: table-colored\n\nCell Phone Type  | Frequency | Proportion\n------------- | ------------- | -----------\nAndroid  | 458 | 0.203\niPhone  | 437 | 0.194\nBlackberry | 141 | 0.063\nNon Smartphone | 924 | 0.41\nNo Cell Phone | 293 | 0.13\nTotal | 2253 | 1.000\n\n:::\n\nProportions and percentages can be used interchangeably\n\n\n\n## Bar Chart/Plot/Graph\n\nIn a barplot, the height of the bar corresponds to the number of cases falling in each category\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](Day3_files/figure-revealjs/unnamed-chunk-1-1.png){fig-align='center' width=50%}\n:::\n:::\n\n\n\n\n\n## Two qualitative Variables\n\nLook at the relationship between two qualitative variables\n- Relationship status\n- Gender\n\n::: table-colored\n|  | Female | Male | Total |\n| :--- | :---: | :---: | :---: |\n| In a Relationship | 32 | 10 | 42 |\n| It's Complicated | 12 | 7 | 19 |\n| Single | 63 | 45 | 108 |\n| Total | 107 | 62 | 169 |\n:::\n\nWe add a second dimension to a frequency table to account for the second qualitative variable\n\n\n\n\n## Relationship status and Gender\n\n::: eqt\n\nProportion of students in a relationship that are female?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.relation.female <- 32/42\nround(prop.relation.female,2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.76\n```\n\n\n:::\n:::\n\n\n\n<br>\n\nProportion of students in a relationship that are male?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.relation.male <- 10/42\nround(prop.relation.male,2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.24\n```\n\n\n:::\n:::\n\n\n\n:::\n\n\n\n\n## Relationship status and Gender\n\n::: eqt\nProportion of males that are in a relationship?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.male <- 10/62\nround(prop.male,2) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.16\n```\n\n\n:::\n:::\n\n\n\nProportion of females that are in a relationship?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.female <- 32/107\nround(prop.female,2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3\n```\n\n\n:::\n:::\n\n\n:::\n\n\n\n[Statkey for Data Visualization: [https://www.lock5stat.com/StatKey/index.html](https://www.lock5stat.com/StatKey/index.html)]{.footer}\n\n\n\n## Difference in proportions\n\n::: bql\n::: font80\n\nA difference in proportions is a difference in proportions for one qualitative variable calculated for different levels of the other qualitative variable\n\n - Example: Difference in proportions of male and female that are in a relationship:\n\n$$\n\\begin{align*}\n \\hat{p}_F - \\hat{p}_M = \\frac{32}{107} - \\frac{10}{62} = 0.14\n\\end{align*}\n$$\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# R-code\nprop.female <- 32/107\nprop.male <- 10/62\nprop.diff <- prop.female - prop.male\nround(prop.diff,2) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.14\n```\n\n\n:::\n:::\n\n\n\n\n\n:::\n:::\n\n\n## Student Survey\n\nDataset on 362 responses to a student survey given at one college\n\n\n::: font50\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Year      |Gender |Smoke | Exercise| TV| Height| Weight| Siblings| BirthOrder|  GPA| Pulse|\n|:---------|:------|:-----|--------:|--:|------:|------:|--------:|----------:|----:|-----:|\n|Senior    |M      |No    |       10|  1|     71|    180|        4|          4| 3.13|    54|\n|Sophomore |F      |Yes   |        4|  7|     66|    120|        2|          2| 2.50|    66|\n|FirstYear |M      |No    |       14|  5|     72|    208|        2|          1| 2.55|   130|\n|Junior    |M      |No    |        3|  1|     63|    110|        1|          1| 3.10|    78|\n|Sophomore |F      |No    |        3|  3|     65|    150|        1|          1| 2.70|    40|\n|Sophomore |F      |No    |        5|  4|     65|    114|        2|          2| 3.20|    80|\n|FirstYear |F      |No    |       10| 10|     66|    128|        1|          1| 2.77|    94|\n|Sophomore |M      |No    |       13|  8|     74|    235|        1|          1| 3.30|    77|\n|Junior    |F      |No    |        3|  6|     61|     NA|        2|          2| 2.80|    60|\n|FirstYear |F      |No    |       12|  1|     60|    115|        7|          8| 3.70|    94|\n\n\n:::\n:::\n\n\n\n:::\n\n\n\n# Distribution\n\n> In the given dataset, there are multiple variables (such as Gender, Smoke, Exercise, Height, Weight, etc.) for different students across various academic years.\n\n\nKnowing the distribution of each variable can help us identify relationships, trends, and potential anomalies in the data.\n\n\n\n\n::: middle-align-xy\n\n\n## Distribution \n\n<br>\n\n::: green-h\n\"The distribution of the variable Y\"\n\n- describes its center, variability and shape\n- use both numbers and graphics\n:::\n\n:::\n\n\n## Center: Mean or Average\n\n::: bqt\nMean: average value in a sample or population\n\n- $\\bar{y} = \\dfrac{\\sum_{i=1}^ny_i}{n}$ is an average of $n$ values $y_i$ in a sample\n- $\\mu$ is an average value of $y$ in a population\n\n:::\n\n\n## Student Survey \n\n::: eqt\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsurvey <- read.csv(\"https://raw.githubusercontent.com/deepbas/statdatasets/main/StudentSurvey.csv\")\nmean(survey$Pulse) # the command `mean` computes an average\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 69.57459\n```\n\n\n:::\n:::\n\n\n:::\n\n::: green-h\nThe mean pulse rate for this sample of students is $\\bar{y} = 69.6$ beats per minute.\n:::\n\n\n\n\n## Center: Median\n\n::: bql\nMedian: the middle value when the data are ordered\n\n- The median splits the data in half\n- $m$ is the median value in a sample\n- $M$ is the median value in a population\n\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmedian(survey$Pulse) # the command `median` computes an median\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 70\n```\n\n\n:::\n:::\n\n\n\n::: green-h\nThe median pulse rate for this sample of students is $m = 70$ beats per minute. \n:::\n\n\n\n## Variability: Standard Deviation\n\n::: bq\n\nStandard Devation (SD): average deviation from center in a sample or population\n\n- $s = \\sqrt{ \\dfrac{\\sum_{i=1}^n(y_i - \\overline{y})^2}{n-1}}$ is the SD of $n$ values $y_i$ in a sample\n- $\\sigma$ is the SD of values of $y$ in a population\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsd(survey$Pulse) # the command `sd` computes an average\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 12.20514\n```\n\n\n:::\n:::\n\n\n\n::: green-h\nThe SD of pulse rates for this sample of students is $s = 12.2$ beats per minute. The \"average\" deviation of individual pulse rates around the mean value is about 12.2 beats per minute.\n:::\n\n\n",
    "supporting": [
      "Day3_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}