{
  "hash": "2755bbaab37f1c8965e7c54b9fcc50ac",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Day 4\"\ntitle-slide-attributes:\n  data-background-image: images/lake.jpg\n  data-background-size: contain\n  data-background-opacity: \"0.5\"\nsubtitle: \"Math 216: Statistical Thinking\"\nauthor: \"Bastola\"\nformat:\n  revealjs:\n    html-math-method: mathjax\n    mathjax-url: \"https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/MathJax.js\" \n    theme: [default, scss/main.scss]\n    slide-number: true\n    preview-links: auto\n    history: true\n    chalkboard: \n      src: drawings.json\n    transition: slide\n    background-transition: fade    \n    touch: false\n    controls: true\n---\n\n\n\n\n\n\n\n## Recap: Student Survey \n\nDataset on 362 responses to a student survey given at one college\n\n\n::: font50\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Year      |Gender |Smoke | Exercise| TV| Height| Weight| Siblings| BirthOrder|  GPA| Pulse|\n|:---------|:------|:-----|--------:|--:|------:|------:|--------:|----------:|----:|-----:|\n|Senior    |M      |No    |       10|  1|     71|    180|        4|          4| 3.13|    54|\n|Sophomore |F      |Yes   |        4|  7|     66|    120|        2|          2| 2.50|    66|\n|FirstYear |M      |No    |       14|  5|     72|    208|        2|          1| 2.55|   130|\n|Junior    |M      |No    |        3|  1|     63|    110|        1|          1| 3.10|    78|\n|Sophomore |F      |No    |        3|  3|     65|    150|        1|          1| 2.70|    40|\n|Sophomore |F      |No    |        5|  4|     65|    114|        2|          2| 3.20|    80|\n|FirstYear |F      |No    |       10| 10|     66|    128|        1|          1| 2.77|    94|\n|Sophomore |M      |No    |       13|  8|     74|    235|        1|          1| 3.30|    77|\n|Junior    |F      |No    |        3|  6|     61|     NA|        2|          2| 2.80|    60|\n|FirstYear |F      |No    |       12|  1|     60|    115|        7|          8| 3.70|    94|\n\n\n:::\n:::\n\n\n\n:::\n\n\n\n## Histogram\n\n::: panel-tabset\n\n### Plot\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](Day4_files/figure-revealjs/unnamed-chunk-2-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n### Code\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(survey, aes(x = Pulse)) +\n  geom_histogram(binwidth = 5, col = \"gold\", fill = \"maroon\") +\n  labs(\n    title = \"Histogram of pulse rates\",\n    x = \"Pulse\",\n    y = \"Count\"\n  ) \n```\n:::\n\n\n\n\n:::\n\n## Histogram: Shape\n\n::: cle9\n- **Histogram:** aggregates values into bins and counts how many cases fall into each bin\n- Pulse rates are symmetrically distributed around a rate of about 70 beats per minute.\n- **Symmetric distributions** are \"centered\" around a mean and median that are roughly the same in value.\n:::\n\n\n\n## Shape and Stats\n\n::: bq\n- Mean and standard deviation are good summary stats of a symmetric distribution.\n- Similar variation to the left and right of the mean so one measure of SD is fine.\n:::\n\n<br>\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)  # for data manipulation\nsurvey %>% summarize(mean = mean(Pulse),\n                     sd = sd(Pulse))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      mean       sd\n1 69.63611 12.10508\n```\n\n\n:::\n:::\n\n\n\n\n\n# Shape: data distribution\n\n::: cle\n\nIf a distribution of data is **approximately bell-shaped**, about 95% of the data should fall within two standard deviations of the sample mean.\n\n- for a sample: 95% of values between $\\bar{y} - 2s$ and $\\bar{y} + 2s$\n- for a population: 95% of values between $\\mu - 2\\sigma$ and $\\mu + 2\\sigma$\n\n:::\n\n## Bell-shaped distribution \n\n::: panel-tabset\n\n### Plot\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Day4_files/figure-revealjs/unnamed-chunk-5-1.png){width=960}\n:::\n:::\n\n\n\n\n### Quiz\n\n::: bq\n\nThe standard deviation for math SAT scores is closest to\n\n(a) 100\n\n(b) 75\n\n(c) 200\n\n(d) 25\n\n:::\n:::\n\n## Standardizing data: z-score\n\n::: lqt\n::: font80\n\nThe z-score of a data value, x, tells us how many standard deviations the value is above or below the mean:\n\n$$z = \\dfrac{x - \\text{mean}}{\\text{SD}}$$\n\n\n- E.g. if a value $x$ has $z=-1.5$ then the value $x$ is 1.5 standard deviations below the mean.\n\n:::\n:::\n\nIf we standardize all values in a bell-shaped distribution, 95% of all z-scores fall between ____ and _____.\n\n\n\n## Shape: Left Skew $\\&$ Right Skew (Histograms)\n\n::: font90\n::: row\n\n::: left\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Day4_files/figure-revealjs/unnamed-chunk-6-1.png){width=960}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(survey$GPA, na.rm =T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.157942\n```\n\n\n:::\n\n```{.r .cell-code}\nmedian(survey$GPA, na.rm = T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.2\n```\n\n\n:::\n:::\n\n\n\n:::\n\n\n::: right\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Day4_files/figure-revealjs/unnamed-chunk-8-1.png){width=960}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(survey$Exercise, na.rm =T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9.048747\n```\n\n\n:::\n\n```{.r .cell-code}\nmedian(survey$Exercise, na.rm = T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 8\n```\n\n\n:::\n:::\n\n\n\n:::\n:::\n:::\n\n## Shape: Left Skew $\\&$ Right Skew (Boxplots)\n\n::: font90\n::: row\n::: left\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Day4_files/figure-revealjs/unnamed-chunk-10-1.png){width=960}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(survey$GPA, na.rm =T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.157942\n```\n\n\n:::\n\n```{.r .cell-code}\nmedian(survey$GPA, na.rm = T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.2\n```\n\n\n:::\n:::\n\n\n\n:::\n\n::: right\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Day4_files/figure-revealjs/unnamed-chunk-12-1.png){width=960}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(survey$Exercise, na.rm =T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9.048747\n```\n\n\n:::\n\n```{.r .cell-code}\nmedian(survey$Exercise, na.rm = T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 8\n```\n\n\n:::\n:::\n\n\n\n:::\n:::\n:::\n\n\n## Shape: boxplots\n\n::: bqt\n::: font60\n\nA graphical representation of the distribution of a dataset, showing the median, quartiles, and outliers.\n\n- *Box:* Represents the interquartile range (IQR) between the 1st quartile (Q1) and the 3rd quartile (Q3)\n- *Median:* The middle value of the dataset, represented by a line inside the box\n- *Whiskers:* Extend from the box to the minimum and maximum data points within 1.5 times the IQR\n- *Outliers:* Data points outside of the whiskers, often represented as individual points\n\n:::\n:::\n\n## Shape: boxplots\n\n::: cle4\n::: font90\n[Symmetry:]{.bold-text} If the median is roughly centered within the box, and the whiskers are of similar length, the distribution is likely symmetric.\n\n\n[Skewness:]{.bold-text}\n\n- **Left-skewed:** The median is closer to the upper quartile (Q3), and the left whisker is longer than the right whisker.\n- **Right-skewed:** The median is closer to the lower quartile (Q1), and the right whisker is longer than the left whisker.\n\n:::\n:::\n\n## Elements of a Box Plot: Inner Fences\n\n::: cle3\n::: font70\n**Lower Inner Fence**: \n$$ \\text{Lower inner fence} = Q_L - 1.5 \\times \\text{IQR} $$\n\n**Upper Inner Fence**:\n$$ \\text{Upper inner fence} = Q_U + 1.5 \\times \\text{IQR} $$\n\n\nInner fences are critical for identifying what is typically considered potential mild outliers. These are points that are unusual but not extreme. The 1.5 multiplier stretches beyond the box enough to capture data variability while excluding more extreme values.\n:::\n:::\n\n## Elements of a Box Plot: Outer Fences\n\n::: cle5\n::: font70\n**Lower Outer Fence**:\n$$ \\text{Lower outer fence} = Q_L - 3 \\times \\text{IQR} $$\n\n**Upper Outer Fence**:\n$$ \\text{Upper outer fence} = Q_U + 3 \\times \\text{IQR} $$\n\nOuter fences help in spotting what are often considered extreme outliers. These are data points that are significantly distant from the typical data range, suggesting possible data entry errors, measurement errors, or novel findings worthy of further investigation.\n:::\n:::\n\n## Outliers\n\n::: fsp\n\n**Mild Outliers** fall between the inner and outer fences and **Extreme Outliers** fall beyond the outer fences.\n\nDifferentiating between mild and extreme outliers is crucial for accurate data analysis, as it helps in determining whether to include or exclude certain data points in statistical calculations. This categorization can impact the conclusions drawn from the data.\n:::\n\n\n\n## Adding a qualitative variable: stats\n\n::: font70\n::: out-t\nUse `group_by()` and `summarise()` to get summary statistics using `dplyr` package to compare distributions across different levels of a qualitative variable\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nsurvey %>%\n  group_by(Smoke) %>%\n  summarise(Min = min(Pulse),\n            Q1 = quantile(Pulse, 0.25),\n            Median = median(Pulse),\n            Mean = mean(Pulse),\n            Q3 = quantile(Pulse, 0.75),\n            Max = max(Pulse),\n            SD = sd(Pulse),\n            N = n()) %>% \n  knitr::kable(caption = \"Summary Stats of Smoke Categories\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Summary Stats of Smoke Categories\n\n|Smoke | Min| Q1| Median|     Mean| Q3| Max|       SD|   N|\n|:-----|---:|--:|------:|--------:|--:|---:|--------:|---:|\n|No    |  35| 61|     69| 69.34069| 77| 130| 12.14980| 317|\n|Yes   |  42| 65|     72| 71.81395| 79|  96| 11.67671|  43|\n\n\n:::\n:::\n\n\n\nSmoker have a slightly higher mean pulse rate than non-smokers (71.8 vs. 69.3).\n\n:::\n\n\n## Side-by-side Histogram\n\n::: panel-tabset\n\n### Plot\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Day4_files/figure-revealjs/cat-graphics-1-1.png){width=960}\n:::\n:::\n\n\n\n### Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nggplot(survey, aes(x=Pulse)) + \n  geom_histogram(binwidth = 4, fill=\"maroon\", col = \"gold\") +\n  facet_wrap(~Smoke)  # to plot by category of Smoke\n```\n:::\n\n\n:::\n\n## Side-by-side boxplot\n\n\n::: panel-tabset\n\n### Plot\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Day4_files/figure-revealjs/unnamed-chunk-15-1.png){width=960}\n:::\n:::\n\n\n\n### Code\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Create boxplots using facet_wrap()\nggplot(survey, aes(x = Smoke, y = Pulse)) +\n  geom_boxplot(fill = c(\"maroon\", \"purple\"), col = \"darkgreen\") +\n  labs(x = \"Smoking Status\", y = \"Pulse Rate\")\n```\n:::\n\n\n\n:::\n\n\n## Stacked bar graph \n\n::: panel-tabset\n\n### Plot\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Day4_files/figure-revealjs/jurors-stacked-1.png){width=100%}\n:::\n:::\n\n\n\n\n### Code\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(survey, aes(x = Year, fill = Gender)) + \n  geom_bar(position = \"fill\") + \n  scale_fill_manual(values = c(\"maroon\", \"gold\")) +\n  labs(title = \"Proportional Distribution by Year and Gender\", \n       y = \"proportion\", \n       x = \"year\", \n       fill = \"Gender\") \n```\n:::\n\n\n\n:::\n\n## Stacked bar graph (counts)\n\n::: panel-tabset\n\n### Plot\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Day4_files/figure-revealjs/jurors-stacked-counts-1.png){width=100%}\n:::\n:::\n\n\n\n\n### Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(survey, aes(x = Year, fill = Gender)) + \n  geom_bar(position = \"stack\") + \n  scale_fill_manual(values = c(\"maroon\", \"gold\")) +\n  labs(title = \"Proportional Distribution by Year and Gender\", \n       y = \"proportion\", \n       x = \"year\", \n       fill = \"Gender\") \n```\n:::\n\n\n\n:::",
    "supporting": [
      "Day4_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}