---
title: "Introduction and Brief Survey"
subtitle: "MATH 216: Statistical Thinking"
format: 
  pdf:
    documentclass: article
    fontsize: 11pt
    geometry: 
      - top=1in
      - bottom=1in
      - left=1.25in
      - right=1.25in
    header-includes:
      - \usepackage{fancyhdr}
      - \usepackage{enumitem}
      - \setlist[enumerate]{leftmargin=*, itemsep=70pt, parsep=10pt}
      - \setlist[enumerate,2]{itemsep=70pt, parsep=10pt} 
      - \setlist[enumerate,1]{after=\vspace{70pt}} 
      - \pagestyle{fancy}
      - \fancyhead{}
      - \fancyfoot[C]{\vspace{2mm} Fall 2024}
---

\vspace{-0.5in} 

\begin{center}
\textbf{Name: \dotfill \hfill Date: \dotfill}
\end{center}

Please answer the following questions to help me better understand your expectations and background. **Any complete in-person submissions during the first week of classes to my office at HS 130 during office hours will receive extra credit.**

1. **What are your learning goals for this course?**


2. **Are there any concerns or challenges you foresee in this course? How can I assist you in overcoming them?**


3. **Major or possible major area (check all that apply):**
   - [ ] Statistics/Data Science
   - [ ] Mathematics
   - [ ] Computer Science
   - [ ] Natural Sciences (biology, physics, etc.)
   - [ ] Social Sciences (economics, political sciences, etc.)
   - [ ] Liberal Arts, Business, or Education


4. **What is your statistics background?**
   - [ ] AP Stats or similar high school class
   - [ ] Some stats in high school (but not a class)
   - [ ] No stats background
   - [ ] Other: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_


5. **Do you need (extra) help installing R and RStudio on your laptop?**
*If yes, please come to my office as soon as possible after our first lab session.*

   - [ ] Yes
   - [ ] No


6. **Do you know how to access the textbook on MyClasses?**
*If no, you can access our textbook via "VitalSource Course Materials" on MyClasses.*
   - [ ] Yes
   - [ ] No

7. **What resources or support do you think will help you succeed in this course?**


8. **What is your preferred method for communicating with your instructor outside of class time?**


**Key Insight:** This past spring 2024 semester, students who participated in Supplemental Instruction (SI) sessions ten or more times achieved an average GPA of 3.17, whereas those who did not attend SI sessions had an average GPA of 2.21.


**Thank you! I am eagerly looking forward to sharing an engaging, fun-filled, and immensely rewarding semester with each of you! Let's make this journey together one to remember.**